#ifndef _HEADER_LIBARY
#define _HEADER_LIBARY
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
typedef enum{no,yes}bool;
#define LINE_LENGTH 81 // include '\n'
#define NUMBER_BIT 14 // in memory word in RAM
#define CHAR_SIZE_BIT 8 
extern bool error_;

typedef enum{LABEL_CANT_BE_SAVED_WORD,EXPECTED_SPACE_AFTER_LABEL,LABEL_TOO_LONG_MISSING,EXTRA_STRING_B4_STRING,LABEL_ALREADY_EXISTS
  ,EXTRA_STRING_B4_DATA,EXTRA_STRING_B4_EXTERN,EXTERN_INVALID_LABEL,EXTERN_TOO_MANY_OPERANDS,STRING_OPERAND_NOT_VALID
  ,DATA_UNEXPECTED_COMMA,DATA_UNEXPECTED_DECIMAL_POINT,DATA_DOUBLE_COMMAS_ROW,DATA_EXPECTED_NUM,DATA_OUT_RANGE
  ,EXTRA_STRING_OPCODE_LABEL,EXTRA_STRING_OPCODE,COMMAND_NOT_FOUND,STRING_B4_ENTRY,ENTRY_NO_LABEL,EXTERN_NO_LABEL,
  ENTRY_TOO_MANY_OPERANDS,EXPECTED_COMMA_BETWEEN_OPERANDS,COMMAND_INVALID_OPERANDS_METHODS
  ,COMMAND_INVALID_NUMBER_OF_OPERANDS,OPERANDS_UNEXPECTED_DECIMAL_POINT,OPERANDS_INVALID_NUM,OPERANDS_NUMBER_OUT_RANGE
  ,LABEL_NAME_DOSENT_EXISTS_ENTRY,LABEL_OPERANDS_DOSENT_EXISTS,DIRECTIVE_NO_PARAMS,OPERAND_CANT_B_NUMBER,EXPECTED_LABEL_AFTER_OPCODE
  ,EXTRA_STRING_AFTER_OPERAND,JMP_EXPECTED_PARENTHESIS,COMMAND_INVALID_NUMBER_OF_PARAMTERS,CANT_BE_WHITE_SPACE_IN_PARAMTERS
  ,DATA_START_COMMA,EXTRA_STRING_AFTER_COMMAND,LABEL_INVALID_FIRST_CHAR,LABEL_ONLY_ALPHANUMERIC_DIGIT,STRING_TOO_MISSING_OPERANDS
  ,LABEL_CANT_BE_EXTERN,NO_ERROR}ERROR_ENUM;

#endif
